In [16]:
import pandas as pd
import numpy as np
import importlib
import mystats

In [8]:
# --- Zadanie 1 ---

dane = [12, 3, 5, 8, 21, 15, 1]

wynik_mediany = mystats.median(dane)

print(f"Dane: {dane}")
print(f"Mediana: {wynik_mediany}")

Dane: [12, 3, 5, 8, 21, 15, 1]
Mediana: 8

In [10]:
# --- Zadanie 2 ---

importlib.reload(mystats)
test_data = [10, 12, 11, 13, 12, 100, 2]
tm = mystats.trimmed_mean(test_data, 0.15)

print(f"Dane testowe: {test_data}")
print(f"Średnia ucinana: {tm:.2f}")

Dane testowe: [10, 12, 11, 13, 12, 100, 2]
Średnia ucinana: 11.60

In [13]:
iris = pd.read_csv('iris.data')

iris.head()

,sepal length in cm,sepal width in cm,petal length in cm,petal width in cm,class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa

In [15]:
# --- ZADANIE 3 ---

iris_numeric = iris.select_dtypes(include=['number'])

srednia_globalna = iris_numeric.mean()
print("Średnia globalna dla wszystkich cech:")
print(srednia_globalna)
print("-" * 30)

srednia_grupowana = iris.groupby('class').mean()
print("Średnia dla poszczególnych klas (gatunków):")
print(srednia_grupowana)

Średnia globalna dla wszystkich cech:
sepal length in cm    5.843333
sepal width in cm     3.054000
petal length in cm    3.758667
petal width in cm     1.198667
dtype: float64
------------------------------
Średnia dla poszczególnych klas (gatunków):
                 sepal length in cm  sepal width in cm  petal length in cm  \
class
Iris-setosa                   5.006              3.418               1.464
Iris-versicolor               5.936              2.770               4.260
Iris-virginica                6.588              2.974               5.552

                 petal width in cm
class
Iris-setosa                  0.244
Iris-versicolor              1.326
Iris-virginica               2.026

In [17]:
# --- ZADANIE 4 ---


red_wine = pd.read_csv('winequality-red.csv', sep=';')
white_wine = pd.read_csv('winequality-white.csv', sep=';')

red_wine['color'] = 'red'
white_wine['color'] = 'white'

wine = pd.concat([red_wine, white_wine], ignore_index=True)

features = wine.drop(columns=['quality', 'color'])
variances = features.var().sort_values()

print("Cechy uszeregowane według wariancji (rosnąco):")
print(variances)
print("-" * 30)

var_by_quality = wine.drop(columns='color').groupby('quality').var()
print("Wariancja cech w podziale na jakość (quality):")
display(var_by_quality)

mean_var_per_quality = var_by_quality.mean(axis=1)
print("\nUśredniona wariancja dla każdej klasy jakości:")
print(mean_var_per_quality)

std_by_color = wine.drop(columns='quality').groupby('color').std()
print("\nOdchylenie standardowe w podziale na kolor wina:")
display(std_by_color)

Cechy uszeregowane według wariancji (rosnąco):
density                    0.000009
chlorides                  0.001227
citric acid                0.021117
sulphates                  0.022143
pH                         0.025853
volatile acidity           0.027105
alcohol                    1.422561
fixed acidity              1.680740
residual sugar            22.636696
free sulfur dioxide      315.041192
total sulfur dioxide    3194.720039
dtype: float64
------------------------------
Wariancja cech w podziale na jakość (quality):

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
quality,,,,,,,,,,,
3,3.054989,0.116904,0.030106,22.379724,0.003846,3598.839368,12575.774713,0.000008,0.045474,0.016127,1.224336
4,1.599783,0.052584,0.033153,14.532382,0.002215,355.908005,3755.571054,0.000006,0.035491,0.027039,0.972044
5,1.587604,0.031891,0.025737,24.943144,0.001765,344.677016,3694.555990,0.000006,0.024768,0.020064,0.663273
6,1.667174,0.021632,0.020306,23.894861,0.000951,283.434310,3075.189393,0.000009,0.025921,0.021533,1.268983
7,1.882771,0.013641,0.012426,16.323577,0.000475,222.763414,2298.599952,0.000009,0.025487,0.025740,1.438410
8,1.316148,0.014246,0.010495,17.434524,0.000246,295.677245,1775.378576,0.000008,0.024782,0.027520,1.635640
9,0.967000,0.003320,0.006730,14.132000,0.000055,180.300000,393.000000,0.000010,0.006870,0.008580,1.027000

Uśredniona wariancja dla każdej klasy jakości:
quality
3    1472.862327
4     375.339432
5     369.684660
6     307.776825
7     231.007809
8     190.138130
9      53.586506
dtype: float64

Odchylenie standardowe w podziale na kolor wina:

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
color,,,,,,,,,,,
red,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668
white,0.843868,0.100795,0.121020,5.072058,0.021848,17.007137,42.498065,0.002991,0.151001,0.114126,1.230621

In [18]:
# --- ZADANIE 5 ---

features_wine = wine.drop(columns=['quality', 'color'])

kwartyle = features_wine.quantile([0.25, 0.5, 0.75])

print("Wartości kwartyli dla cech w zbiorze Wine Quality:")
display(kwartyle)

Wartości kwartyli dla cech w zbiorze Wine Quality:

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0.25,6.4,0.23,0.25,1.8,0.038,17.0,77.0,0.99234,3.11,0.43,9.5
0.50,7.0,0.29,0.31,3.0,0.047,29.0,118.0,0.99489,3.21,0.51,10.3
0.75,7.7,0.40,0.39,8.1,0.065,41.0,156.0,0.99699,3.32,0.60,11.3

In [25]:
wine.columns = [col.replace(' ', '_') for col in wine.columns]

print(wine.columns)

Index(['fixed_acidity', 'volatile_acidity', 'citric_acid', 'residual_sugar',
       'chlorides', 'free_sulfur_dioxide', 'total_sulfur_dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'color'],
      dtype='str')

In [26]:
# --- ZADANIE 6 ---

progu_cukru = wine['residual_sugar'].quantile(0.95)

print(f"Wartość odcinająca 95% wyników (P95): {progu_cukru:.2f}")

najslodsze_wina = wine[wine['residual_sugar'] > progu_cukru]

print(f"Liczba znalezionych pozycji: {len(najslodsze_wina)}")
display(najslodsze_wina)

Wartość odcinająca 95% wyników (P95): 15.00
Liczba znalezionych pozycji: 324

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,color
480,10.6,0.280,0.39,15.50,0.069,6.0,23.0,1.00260,3.12,0.66,9.20,5,red
1434,10.2,0.540,0.37,15.40,0.214,55.0,95.0,1.00369,3.18,0.77,9.00,6,red
1435,10.2,0.540,0.37,15.40,0.214,55.0,95.0,1.00369,3.18,0.77,9.00,6,red
1599,7.0,0.270,0.36,20.70,0.045,45.0,170.0,1.00100,3.00,0.45,8.80,6,white
1606,7.0,0.270,0.36,20.70,0.045,45.0,170.0,1.00100,3.00,0.45,8.80,6,white
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6290,6.9,0.190,0.31,19.25,0.043,38.0,167.0,0.99954,2.93,0.52,9.10,7,white
6293,6.9,0.190,0.31,19.25,0.043,38.0,167.0,0.99954,2.93,0.52,9.10,7,white
6347,6.1,0.340,0.24,18.35,0.050,33.0,184.0,0.99943,3.12,0.61,9.30,5,white
6348,6.2,0.350,0.25,18.40,0.051,28.0,182.0,0.99946,3.13,0.62,9.30,6,white
6377,5.8,0.315,0.19,19.40,0.031,28.0,106.0,0.99704,2.97,0.40,10.55,6,white