In [5]:
import numpy as np
import pandas as pd

In [6]:
# --- ZADANIE 1 ---
dane = list(range(1, 101))
indeks = [f"ean_{n:03}" for n in range(1, 101)]
zadanie_1 = pd.Series(data=dane, index=indeks)
zadanie_1.head()

ean_001    1
ean_002    2
ean_003    3
ean_004    4
ean_005    5
dtype: int64

In [7]:
# --- ZADANIE 2 ---
podstawa = np.arange(1, 11).reshape(10, 1)
wykladniki = np.arange(1, 11)
tablica_np = np.power(podstawa, wykladniki)
nazwy_kolumn = ['base'] + [f'pow_{n}' for n in range(2, 11)]
df_potegi = pd.DataFrame(data=tablica_np, columns=nazwy_kolumn)
df_potegi

,base,pow_2,pow_3,pow_4,pow_5,pow_6,pow_7,pow_8,pow_9,pow_10
0,1,1,1,1,1,1,1,1,1,1
1,2,4,8,16,32,64,128,256,512,1024
2,3,9,27,81,243,729,2187,6561,19683,59049
3,4,16,64,256,1024,4096,16384,65536,262144,1048576
4,5,25,125,625,3125,15625,78125,390625,1953125,9765625
5,6,36,216,1296,7776,46656,279936,1679616,10077696,60466176
6,7,49,343,2401,16807,117649,823543,5764801,40353607,282475249
7,8,64,512,4096,32768,262144,2097152,16777216,134217728,1073741824
8,9,81,729,6561,59049,531441,4782969,43046721,387420489,3486784401
9,10,100,1000,10000,100000,1000000,10000000,100000000,1000000000,10000000000

In [8]:
# --- ZADANIE 3 ---
wspoldzieli = df_potegi.values.base is tablica_np
print(f"Czy df_potegi współdzieli pamięć? {wspoldzieli}")

df_potegi_shared = pd.DataFrame(data=tablica_np, copy=False)
df_potegi_shared.columns = nazwy_kolumn # nadajemy te same nazwy kolumn

# 3. Sprawdzamy ponownie dla nowej ramki
wspoldzieli_nowa = df_potegi_shared.values.base is tablica_np
print(f"Czy df_potegi_shared współdzieli pamięć? {wspoldzieli_nowa}")

Czy df_potegi współdzieli pamięć? False
Czy df_potegi_shared współdzieli pamięć? True

In [9]:
# --- ZADANIE 4 ---


print("Sytuacja przed optymalizacją:")
print(df_potegi_shared.dtypes)
pamiec_przed = df_potegi_shared.memory_usage(deep=True).sum()
print(f"Pamięć przed: {pamiec_przed} bajtów")


df_zad4 = df_potegi_shared.apply(pd.to_numeric, downcast='integer')


print("\nSytuacja po optymalizacji:")
print(df_zad4.dtypes)
pamiec_po = df_zad4.memory_usage(deep=True).sum()
print(f"Pamięć po: {pamiec_po} bajtów")

# 4. Uzasadnienie
roznica = pamiec_przed - pamiec_po
print(f"\nUzasadnienie: Poprzez zmianę typów (np. z int64 na mniejsze int8 tam, gdzie to możliwe), zaoszczędzono {roznica} bajtów.")

Sytuacja przed optymalizacją:
base      int64
pow_2     int64
pow_3     int64
pow_4     int64
pow_5     int64
pow_6     int64
pow_7     int64
pow_8     int64
pow_9     int64
pow_10    int64
dtype: object
Pamięć przed: 932 bajtów

Sytuacja po optymalizacji:
base       int8
pow_2      int8
pow_3     int16
pow_4     int16
pow_5     int32
pow_6     int32
pow_7     int32
pow_8     int32
pow_9     int32
pow_10    int64
dtype: object
Pamięć po: 472 bajtów

Uzasadnienie: Poprzez zmianę typów (np. z int64 na mniejsze int8 tam, gdzie to możliwe), zaoszczędzono 460 bajtów.

In [10]:
# --- ZADANIE 5 ---

iris = pd.read_csv('iris.data')


iris.head()

,sepal length in cm,sepal width in cm,petal length in cm,petal width in cm,class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa

In [11]:
# --- ZADANIE 6 ---

iris.columns = [col.replace(' ', '_') for col in iris.columns]

iris.head(10)

,sepal_length_in_cm,sepal_width_in_cm,petal_length_in_cm,petal_width_in_cm,class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
5,5.4,3.9,1.7,0.4,Iris-setosa
6,4.6,3.4,1.4,0.3,Iris-setosa
7,5.0,3.4,1.5,0.2,Iris-setosa
8,4.4,2.9,1.4,0.2,Iris-setosa
9,4.9,3.1,1.5,0.1,Iris-setosa

In [13]:
# --- ZADANIE 7 ---


mem_shallow = iris.memory_usage().sum()
mem_deep = iris.memory_usage(deep=True).sum()

print(f"Pamięć (bez deep): {mem_shallow} bajtów")
print(f"Pamięć (z deep=True): {mem_deep} bajtów")
print("-" * 30)

float_cols = iris.select_dtypes(include=['float64']).columns
print(f"Kolumny do zmiany: {list(float_cols)}")

iris_smaller = iris.copy()
iris_smaller[float_cols] = iris_smaller[float_cols].astype('float32')

mem_smaller_deep = iris_smaller.memory_usage(deep=True).sum()

print(f"Typy danych w iris_smaller:\n{iris_smaller.dtypes}")
print(f"\nNowa pamięć (deep=True): {mem_smaller_deep} bajtów")

oszczednosc = mem_deep - mem_smaller_deep
print(f"\nUzasadnienie: Zmiana typu z float64 na float32 zmniejszyła wagę ramki o {oszczednosc} bajtów.")

Pamięć (bez deep): 6132 bajtów
Pamięć (z deep=True): 14282 bajtów
------------------------------
Kolumny do zmiany: ['sepal_length_in_cm', 'sepal_width_in_cm', 'petal_length_in_cm', 'petal_width_in_cm']
Typy danych w iris_smaller:
sepal_length_in_cm    float32
sepal_width_in_cm     float32
petal_length_in_cm    float32
petal_width_in_cm     float32
class                     str
dtype: object

Nowa pamięć (deep=True): 11882 bajtów

Uzasadnienie: Zmiana typu z float64 na float32 zmniejszyła wagę ramki o 2400 bajtów.

In [15]:
# --- ZADANIE 8 ---

iris.to_clipboard()


iris_from_clipboard = pd.read_clipboard()

iris_from_clipboard.head()

,sepal_length_in_cm,sepal_width_in_cm,petal_length_in_cm,petal_width_in_cm,class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa

In [18]:
!pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\kubuncio\pycharmprojects\lab01_wpd_poprawiony\.venv\lib\site-packages (23.0.1)

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [21]:
!pip install fastparquet

Collecting fastparquet
  Downloading fastparquet-2025.12.0-cp313-cp313-win_amd64.whl.metadata (4.6 kB)
Requirement already satisfied: pandas>=1.5.0 in c:\users\kubuncio\pycharmprojects\lab01_wpd_poprawiony\.venv\lib\site-packages (from fastparquet) (3.0.1)
Requirement already satisfied: numpy in c:\users\kubuncio\pycharmprojects\lab01_wpd_poprawiony\.venv\lib\site-packages (from fastparquet) (2.4.3)
Collecting cramjam>=2.3 (from fastparquet)
  Downloading cramjam-2.11.0-cp313-cp313-win_amd64.whl.metadata (681 bytes)
Collecting fsspec (from fastparquet)
  Downloading fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: packaging in c:\users\kubuncio\pycharmprojects\lab01_wpd_poprawiony\.venv\lib\site-packages (from fastparquet) (26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kubuncio\pycharmprojects\lab01_wpd_poprawiony\.venv\lib\site-packages (from pandas>=1.5.0->fastparquet) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\kubuncio\pycharmprojects\lab01_wpd_poprawiony\.venv\lib\site-packages (from pandas>=1.5.0->fastparquet) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\kubuncio\pycharmprojects\lab01_wpd_poprawiony\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.17.0)
Downloading fastparquet-2025.12.0-cp313-cp313-win_amd64.whl (667 kB)
   ---------------------------------------- 0.0/667.4 kB ? eta -:--:--
   ---------------------------------------- 667.4/667.4 kB 9.8 MB/s eta 0:00:00
Downloading cramjam-2.11.0-cp313-cp313-win_amd64.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 1.7/1.7 MB 24.8 MB/s eta 0:00:00
Downloading fsspec-2026.2.0-py3-none-any.whl (202 kB)
Installing collected packages: fsspec, cramjam, fastparquet

   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   -------------------------- ------------- 2/3 [fastparquet]
   ---------------------------------------- 3/3 [fastparquet]

Successfully installed cramjam-2.11.0 fastparquet-2025.12.0 fsspec-2026.2.0

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [22]:
# --- ZADANIE 9  ---


iris.to_parquet('iris.parquet', engine='fastparquet')

iris.to_json('iris.json')
iris.to_pickle('iris.pkl')

print("Zadanie zakończone sukcesem przy użyciu silnika fastparquet!")

Zadanie zakończone sukcesem przy użyciu silnika fastparquet!